# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NcUGRAH+EjHo9IHdtJ2ZPTOytg0OPmv+cLcRYKrcQDEYuCNjevanMiUULXEoj84jR2verYInUjrXhG8RPOP6dKqVkcOgIx4hd7NNnNXkQn4/qSeZBSyiNUS/PwjboScw/7DcqbfSe8U9NwOnSbL10rl88mbxnAHBYegQH2dJAVlm4jooZUmsQJzz49016YI6M05UA98nMZCgZ5Nk/na0Z4lCgyAyNwuQPUlImzEsoVsMrsh2Gkgd77s3aYWGDAbiqQ8f9ilsN/uLLMDMIR14Yn9/fwgfgNMO0AePbaKzJkrVBSL90dbz2UZo93uyMt4alB5+q/c0jN7OfiMvg0Amg/VP9KIr3V5+zc46IWLFBMaKlNsIFmASscJcJhosHLy9dgSMmP95/WlqjJbGZdvcwAfENMVAkhLc8EyvujH3ZvRZBdClAk2Xwn6tGHMBjtwYsGaAv4Zm5Jzv+6K1WtEU202dxQjTtN6XO8SaXsKeAp5gWZHqP0TbtHIvUECiaa7n0kW0w1nH6Fen5I4RVYmbE3oZSPMUBvHsW1RmmDAgFBUDU7FysHZhCCtbtNjEjNIZEghxqmpiXogvrlcXyrld9Q4uxxLC/Ao/qhN5bJq9oHmQdwKYPsb3SuNYr1wJcLYA4NKqn9nAwd+PhBsuNLde9vrBtjYNGC0PAT40Y3cVogI="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
