travis:
  secure:
    BINSTAR_TOKEN: Ww4v9J6bFQeo4TzjS40zzu4b8EGr3MADIf6TLRjaDsA9cs5BNJkH1+yjPl0uXkmkKqvXLJJNPzHjofEx5fSvDtbe/ruQOqm7gOurC45n/iszH2IFjBrcFGvHupT8TF8VmGuHTG3pZcBPuyGqoB8ESRzOiP0GBWl3lWPCNlBPxYKrOfIseSsO9YAPoJVscBbZc99ga9eZG9AXSKPDPgvv3BtrDWeBpD/xCIWBprXsbQzFkXMyf+6nVuDKftINtjfKcguxvNDBnrK/AyKmubJFR1Rv4amnNqVAYZ6XFFxnMg5Kh+sKk0aBEpzGcuW1cgr7gtMO8/W0mRA9YU1M/k9rTzJRgz4wwAyrjQ10c2I1KXF+neg+V0K8fMkjHXnOP1HQRUSzIyDMcBnrzUsdqX5AZpTnLvfrC97XVKj9MJS0OxxsPUxDFPZiZLowQve25BeHu0woDwC0GM1XYuYYvy2Z2QDG0gComF29rwlqtudvWjOaO5H3ah4sajo99wCOimUwpVIU87qCC5xQt5T+81KMSEJHtxWVtB+HF4rNJDWX1dRyWJFW94YPkzzugSbz7Y6f95smY0RrPkIROVmQgU1zV42R0lcoybl05+svijK1DXLXG46fmiuHlZ4MEoxnynYiE8m4dNpBhOjFiPmv0zrqqMSetkxDc8hOT4pwVckGMGg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
