travis:
  secure:
    BINSTAR_TOKEN: DIImH028WVWD+edfkzEHRBV5J/24vSceZLIYIqaAEtP6cjuoipq1XYNvwDeIHKLpASH6VX1Gi9HhFJlq8vjPzi5CXyXTYykV6sN5akSu2eDHmHiuVq2cyUDfcdM96Bmc+rGNvIFM5Du0dDADFUElz95rOsv3S215LHOp3ZQt2BNWDuZiBfc/UxdjWL602zuwoub8GLKW9uv4fcUJ7HeWnFwH0zxNS9hjLZUkRR9puracFYWUkre7zNejVVjyEoVSFQawo30gyJ+Xo09L8C+wEMgxR5hXtX6zwRseMPYCaD/dKRq7myx4+7gNHLmAEVFSA7dAb1mNWQ22mCYfn+uExPXDStov9TlFLiH0tsnK7WJWPgbGrVjlLfdNn78xs6OmcY7sgJbQC6+BYu/4M0+yxBNn7hfVaNoaaWH6Jm4FE08oIjiOQjTFiomS/ntMC4TEe5EovRqV9AXk4XhOg2TC1fA+cpGh1wgQcdkqQ0Fn8dZNjABTK5ofPZAYe0sdht/SGpb6KkiIv9NQwuslAhY2xs70B1lW9A1yxwsTTc9w0fBCsGoWbeIXvEJK4PdTF+e3X0/4DwmS7lHID+g7u90xUt5JKQ9d0XxDDieKlZtiVZSQrT1C9yCL52ozTmaSSUJgGod/cUin2LyejCIrxuCBv6i+pagvp3CIad7OYgpCAXU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
